# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-03 06:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='/images/default.png', upload_to='images'),
            preserve_default=False,
        ),
    ]
