# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-09-05 04:28
from __future__ import unicode_literals

from django.db import migrations

def create_product_picture(apps, schema_editor):
    Products = apps.get_model('collection', 'Products')
    ProductPicture = apps.get_model('collection', 'ProductPicture')
    for product in Products.objects.all():
        ProductPicture.objects.create(image=product.image, product=product)

def populate_product_image(apps, schema_editor):
    Products = apps.get_model('collection', 'Products')
    for product in Products.objects.all():
        product.image = product.pictures.first().image
        product.save()


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0004_productpicture'),
    ]

    operations = [
        migrations.RunPython(create_product_picture, populate_product_image)
    ]
